# Generated by Django 5.0 on 2024-04-24 11:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hamkorlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hamkor_nomi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_turi', models.CharField(max_length=10)),
                ('visa_narxi', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xujjat_nomi', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=300)),
                ('turistlar_soni', models.DecimalField(decimal_places=0, max_digits=6)),
                ('yaratilgan_vaqti', models.DateTimeField(default=datetime.datetime.today)),
                ('hamkor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hamkorlar')),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.visa')),
            ],
            options={
                'ordering': ['-yaratilgan_vaqti'],
            },
        ),
    ]
